[package]
name    = "dns"
version = "0.1.0"
authors = ["Hanno Braun <hanno@braun-embedded.com>"]
edition = "2018"


[dependencies]
anyhow  = "*"
reqwest = "*"
toml    = "*"

[dependencies.serde]
version  = "*"
features = ["derive"]
