[workspace]
members = [
    "sites/archive.braun-odw.eu/rust",
    "sites/hanno.braun-odw.eu/rust",
    "sites/well-known/rust",
    "tools/builder",
    "tools/ssg",
]
default-members = [
    "tools/builder"
]
