[build]
publish = "sites/"
command = "cargo run --bin sites"

# TASK: Set up a development server that continually builds changes, and hook it
#       up to `netlify dev`. This is documented here:
#       https://docs.netlify.com/cli/get-started/#netlify-dev

# Primary domains

[[redirects]]
from   = "https://hanno.braun-odw.eu/*"
to     = "/hanno.braun-odw.eu/:splat"
status = 200
force  = true


# Secondary domains

[[redirects]]
from   = "https://braun-odw.eu/*"
to     = "https://hanno.braun-odw.eu/:splat"
status = 301
force  = true

[[redirects]]
from   = "https://www.braun-odw.eu/*"
to     = "https://hanno.braun-odw.eu/:splat"
status = 301
force  = true

[[redirects]]
from   = "https://braun-odw.netlify.app/*"
to     = "https://hanno.braun-odw.eu/:splat"
status = 301
force  = true
