[build]
publish = "sites/"
command = "cargo run --bin sites"


# Primary domains

[[redirects]]
from   = "https://hanno.braun-odw.eu/*"
to     = "/hanno.braun-odw.eu/:splat"
status = 200
force  = true


# Secondary domains

[[redirects]]
from   = "https://braun-odw.eu/*"
to     = "https://hanno.braun-odw.eu/:splat"
status = 301
force  = true

[[redirects]]
from   = "https://www.braun-odw.eu/*"
to     = "https://hanno.braun-odw.eu/:splat"
status = 301
force  = true

[[redirects]]
from   = "https://braun-odw.netlify.app/*"
to     = "https://hanno.braun-odw.eu/:splat"
status = 301
force  = true
