[build]
publish = "output/"
command = "cargo run --bin builder"

[build.environment]
RUST_LOG = "info"


[dev]
command = "cargo run --bin builder -- --dev"
targetPort = 34480
framework = "#custom"


# Domains

[[redirects]]
from = "https://archive.braun-odw.eu/*"
to = "/archive.braun-odw.eu/:splat"
status = 200
force = true

[[redirects]]
from = "https://braun-odw.netlify.app/*"
to = "https://archive.braun-odw.eu/:splat"
status = 301
force = true
