[build]
publish = "output/"
command = "cargo run --bin sites"

[build.environment]
RUST_LOG = "info"


# TASK: Make this work again. It needs to call something that rebuilds the site
#       application when anything changes.
[dev]
command    = "cargo run --bin builder -- --dev"
targetPort = 34480
framework  = "#custom"


# .well-known directory
#
# Netlify seems to filter any paths beginning with a "." during the deploy
# process, as far as I can tell. This makes the .well-known directory work.

[[redirects]]
from   = "https://braun-odw.eu/.well-known/*"
to     = "/well-known/:splat"
status = 200
force  = true

[[headers]]
for = "/.well-known/matrix/client"
[headers.values]
Access-Control-Allow-Origin = "*"


# Primary domains

[[redirects]]
from   = "https://hanno.braun-odw.eu/*"
to     = "/hanno.braun-odw.eu/:splat"
status = 200
force  = true

[[redirects]]
from   = "https://archive.braun-odw.eu/*"
to     = "/archive.braun-odw.eu/:splat"
status = 200
force  = true


# Secondary domains

[[redirects]]
from   = "https://braun-odw.eu/*"
to     = "https://hanno.braun-odw.eu/:splat"
status = 301
force  = true

[[redirects]]
from   = "https://www.braun-odw.eu/*"
to     = "https://hanno.braun-odw.eu/:splat"
status = 301
force  = true

[[redirects]]
from   = "https://braun-odw.netlify.app/*"
to     = "https://hanno.braun-odw.eu/:splat"
status = 301
force  = true


# Legacy domains

[[redirects]]
from   = "https://hannobraun.de/"
to     = "https://hanno.braun-odw.eu/"
status = 301
force  = true

[[redirects]]
from   = "https://hannobraun.de/*"
to     = "https://archive.braun-odw.eu/:splat"
status = 301
force  = true

[[redirects]]
from   = "https://www.hannobraun.de/*"
to     = "https://hannobraun.de/:splat"
status = 301
force  = true
