[build]
publish = "output/"
command = "cargo run --bin builder"

[build.environment]
RUST_LOG = "info"


[dev]
command = "cargo run --bin builder -- --dev"
targetPort = 34480
framework = "#custom"


# .well-known directory
#
# Netlify seems to filter any paths beginning with a "." during the deploy
# process, as far as I can tell. This makes the .well-known directory work.

[[redirects]]
from = "https://braun-odw.eu/.well-known/*"
to = "/well-known/:splat"
status = 200
force = true

[[headers]]
for = "/.well-known/matrix/client"
[headers.values]
Access-Control-Allow-Origin = "*"


# Domains

[[redirects]]
from = "https://archive.braun-odw.eu/*"
to = "/archive.braun-odw.eu/:splat"
status = 200
force = true

[[redirects]]
from = "https://braun-odw.netlify.app/*"
to = "https://archive.braun-odw.eu/:splat"
status = 301
force = true
