[package]
name    = "builder"
version = "0.1.0"
authors = ["Hanno Braun <hanno@braun-odw.eu>"]
edition = "2018"


[dependencies]
anyhow             = "*"
tracing-subscriber = "*"

[dependencies.ssg]
path = "../ssg"

[dependencies.tokio]
version  = "*"
features = ["full"]
